/**
 * Graph generator — produces the typed InteractKitGraph class.
 *
 * graph.configure({...}) returns a typed App instance with:
 * - Entity handler builders (app.EntityName.method(fn))
 * - Typed proxy getters (app.entityName.method(input))
 * - boot() / stop()
 */

import type { GraphIR } from '../ir.js';

export function generateGraph(graph: GraphIR): string {
  const rootName = graph.root ?? graph.entities[0]?.name;
  if (!rootName) throw new Error('No entities defined');

  const rootEntity = graph.entities.find(e => e.name === rootName);
  if (!rootEntity) throw new Error(`Root entity "${rootName}" not found`);

  // Check if any tools have src attributes (handlers.ts will be generated)
  const hasSrcHandlers = graph.entities.some(e => e.tools.some(t => t.src));

  const lines: string[] = [];

  lines.push('// AUTO-GENERATED by @interactkit/cli — do not edit');
  lines.push("import { InteractKitRuntime, InteractKitApp } from '@interactkit/sdk';");
  lines.push("import { entityTree } from './tree.js';");
  lines.push("import { Registry } from './registry.js';");
  if (hasSrcHandlers) {
    lines.push("import { handlers as srcHandlers } from './handlers.js';");
  }

  // Collect all type imports
  const typeImports = new Set<string>();
  typeImports.add('AddHandlerOverloads');
  typeImports.add('OnOverloads');
  typeImports.add('HandlersConfig');
  for (const comp of rootEntity.components) {
    typeImports.add(`${comp.entity}Proxy`);
  }
  for (const entity of graph.entities) {
    typeImports.add(`${entity.name}HandleBuilder`);
  }
  // Root entity proxy type
  typeImports.add(`${rootName}Proxy`);

  lines.push(`import type { ${[...typeImports].join(', ')} } from './types.js';`);
  lines.push('');

  // ─── App class (returned by configure) ────────────────

  lines.push('class App extends InteractKitApp {');

  // Entity handler builders (app.EntityName.method(fn))
  for (const entity of graph.entities) {
    const entityType = toKebab(entity.name);
    lines.push(`  get ${entity.name}(): ${entity.name}HandleBuilder {`);
    lines.push(`    return this.handleBuilder('${entityType}') as unknown as ${entity.name}HandleBuilder;`);
    lines.push('  }');
  }
  lines.push('');

  // Typed proxy getter for root entity (app.agent.increment({...}))
  const rootCamel = rootName[0].toLowerCase() + rootName.slice(1);
  lines.push(`  get ${rootCamel}(): ${rootName}Proxy {`);
  lines.push(`    return this.proxy('${toKebab(rootName)}') as unknown as ${rootName}Proxy;`);
  lines.push('  }');

  // Typed proxy getters for root's components (app.memory.store({...}))
  for (const comp of rootEntity.components) {
    const proxyPath = `${toKebab(rootName)}.${comp.name}`;
    lines.push(`  get ${comp.name}(): ${comp.entity}Proxy {`);
    lines.push(`    return this.proxy('${proxyPath}') as unknown as ${comp.entity}Proxy;`);
    lines.push('  }');
  }
  lines.push('');

  // Typed addHandler / on overrides
  lines.push('  override addHandler(...args: Parameters<AddHandlerOverloads>): this {');
  lines.push('    (super.addHandler as any)(...args);');
  lines.push('    return this;');
  lines.push('  }');
  lines.push('');
  lines.push('  override on(...args: Parameters<OnOverloads>): this {');
  lines.push('    (super.on as any)(...args);');
  lines.push('    return this;');
  lines.push('  }');

  lines.push('}');
  lines.push('');

  // ─── Graph class (schema, calls configure to get App) ─

  lines.push('class InteractKitGraph extends InteractKitRuntime {');
  lines.push('  constructor() {');
  lines.push('    super(entityTree as any, Registry);');
  lines.push('  }');
  lines.push('');
  lines.push('  override configure(config: Omit<import("@interactkit/sdk").RuntimeConfig, "handlers"> & { handlers?: HandlersConfig }): App {');
  if (hasSrcHandlers) {
    lines.push('    // Merge src-defined handlers with user-provided handlers (user overrides take precedence)');
    lines.push('    const mergedHandlers: Record<string, Record<string, Function>> = {};');
    lines.push('    for (const [key, val] of Object.entries(srcHandlers)) {');
    lines.push('      mergedHandlers[key] = { ...val as Record<string, Function> };');
    lines.push('    }');
    lines.push('    if (config.handlers) {');
    lines.push('      for (const [key, val] of Object.entries(config.handlers)) {');
    lines.push('        if (val) mergedHandlers[key] = { ...mergedHandlers[key], ...val as Record<string, Function> };');
    lines.push('      }');
    lines.push('    }');
    lines.push('    super.configure({ ...config, handlers: mergedHandlers } as any);');
  } else {
    lines.push('    super.configure(config as any);');
  }
  lines.push('    return new App(this);');
  lines.push('  }');
  lines.push('}');
  lines.push('');

  lines.push('export const graph = new InteractKitGraph();');
  lines.push('');

  return lines.join('\n');
}

function toKebab(name: string): string {
  return name.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();
}
