/**
 * Handlers generator — produces a typed handlers config from tool src attributes.
 *
 * Collects all tools with `src` attributes across entities and generates
 * a HandlersConfig object that imports each handler from its source file.
 *
 * Generated output:
 *   import researchHandler from '../../src/tools/research.js';
 *   export const handlers = { Researcher: { research: researchHandler }, ... };
 */

import type { GraphIR } from '../ir.js';

export function generateHandlers(graph: GraphIR): string | null {
  // Collect all entities that have tools with src
  const entries: Array<{ entityName: string; toolName: string; src: string }> = [];

  for (const entity of graph.entities) {
    for (const tool of entity.tools) {
      if (tool.src) {
        entries.push({ entityName: entity.name, toolName: tool.name, src: tool.src });
      }
    }
  }

  if (entries.length === 0) return null;

  const lines: string[] = [];

  lines.push('// AUTO-GENERATED by @interactkit/cli — do not edit');
  lines.push("import type { HandlersConfig } from './types.js';");
  lines.push('');

  // Generate imports — each src gets a unique import name
  const importNames = new Map<string, string>();
  let idx = 0;
  for (const entry of entries) {
    const key = `${entry.entityName}.${entry.toolName}`;
    // Convert src path to relative import from .generated/ dir
    // src is relative to interactkit/ dir, output is in interactkit/.generated/
    const importPath = `../${entry.src}`.replace(/\.ts$/, '.js');
    const importName = `_h${idx++}`;
    importNames.set(key, importName);
    lines.push(`import ${importName} from '${importPath}';`);
  }
  lines.push('');

  // Group by entity
  const byEntity = new Map<string, Array<{ toolName: string; key: string }>>();
  for (const entry of entries) {
    const key = `${entry.entityName}.${entry.toolName}`;
    if (!byEntity.has(entry.entityName)) byEntity.set(entry.entityName, []);
    byEntity.get(entry.entityName)!.push({ toolName: entry.toolName, key });
  }

  // Generate handlers config
  lines.push('export const handlers: HandlersConfig = {');
  for (const [entityName, tools] of byEntity) {
    lines.push(`  ${entityName}: {`);
    for (const { toolName, key } of tools) {
      lines.push(`    ${toolName}: ${importNames.get(key)!},`);
    }
    lines.push('  },');
  }
  lines.push('};');
  lines.push('');

  return lines.join('\n');
}
