/**
 * Registry generator — produces Zod validation schemas.
 *
 * Output matches the format from cli/src/codegen/emit/index.ts
 * so the runtime can consume it without changes.
 */

import type { GraphIR, EntityIR, FieldIR, FieldTypeKind, ValidateIR, ParamIR, ToolIR } from '../ir.js';

export function generateRegistry(graph: GraphIR): string {
  const lines: string[] = [];

  lines.push('// AUTO-GENERATED by @interactkit/cli — do not edit');
  lines.push("import { z } from '@interactkit/sdk';");
  lines.push('');

  // ─── Registry ─────────────────────────────────────────

  lines.push('export const Registry = {');
  lines.push('  entities: {');

  for (const entity of graph.entities) {
    const entityType = toKebab(entity.name);
    lines.push(`    '${entityType}': {`);

    // State
    if (entity.state.length > 0) {
      const fields = entity.state.map(f => `        ${f.name}: ${fieldToZod(f)}`).join(',\n');
      lines.push(`      state: z.object({\n${fields},\n      }),`);
    } else {
      lines.push('      state: z.object({}),');
    }

    // Methods (from tools)
    lines.push('      methods: {');
    for (const tool of entity.tools) {
      const eventName = `${entityType}.${tool.name}`;
      lines.push(`        '${eventName}': {`);
      lines.push(`          input: ${toolInputToZod(tool)},`);
      lines.push(`          result: ${toolOutputToZod(tool)},`);
      lines.push(`          fieldMeta: {},`);
      lines.push('        },');
    }
    lines.push('      },');

    // Components
    const compStr = entity.components.map(c => `{ property: '${c.name}', type: '${toKebab(c.entity)}' }`).join(', ');
    lines.push(`      components: [${compStr}],`);

    // Streams
    const streamStr = entity.streams.map(s => `'${s.name}'`).join(', ');
    lines.push(`      streams: [${streamStr}],`);

    // Refs
    const refStr = entity.refs.map(r => `'${r.name}'`).join(', ');
    lines.push(`      refs: [${refStr}],`);

    // Hooks (empty in v4)
    lines.push('      hooks: [],');

    lines.push('    },');
  }

  lines.push('  },');
  lines.push('} as const;');
  lines.push('');

  // ─── ConfigurableFields ───────────────────────────────

  lines.push('export const ConfigurableFields = {');
  for (const entity of graph.entities) {
    const configurables = entity.state.filter(f => f.configurable);
    if (configurables.length === 0) continue;
    const entityType = toKebab(entity.name);
    lines.push(`  '${entityType}': [`);
    for (const c of configurables) {
      const label = c.configurableLabel ?? c.name;
      const parts = [
        `key: '${c.name}'`,
        `label: '${esc(label)}'`,
        c.configurableGroup ? `group: '${esc(c.configurableGroup)}'` : null,
        `type: '${c.type}'`,
        `validation: ${fieldToZod(c)}`,
      ].filter(Boolean);
      lines.push(`    { ${parts.join(', ')} },`);
    }
    lines.push('  ],');
  }
  lines.push('} as const;');
  lines.push('');

  // ─── Utility types ────────────────────────────────────

  const entityTypes = graph.entities.map(e => `'${toKebab(e.name)}'`);
  lines.push(`export type EntityType = ${entityTypes.join(' | ')};`);

  const allMethods = graph.entities.flatMap(e =>
    e.tools.map(t => `'${toKebab(e.name)}.${t.name}'`)
  );
  lines.push(`export type MethodName = ${allMethods.length > 0 ? allMethods.join(' | ') : 'never'};`);
  lines.push('');

  return lines.join('\n');
}

// ─── Zod code generation ────────────────────────────────

function fieldToZod(field: FieldIR): string {
  let code = baseTypeToZod(field.type, field.items, field.values, field.children);
  code = applyValidation(code, field.type, field.validate);
  if (field.optional) code += '.optional()';
  return code;
}

function paramToZod(param: ParamIR): string {
  let code = baseTypeToZod(param.type, param.items, param.values, param.children);
  code = applyValidation(code, param.type, param.validate);
  if (param.optional) code += '.optional()';
  return code;
}

function baseTypeToZod(type: FieldTypeKind, items?: FieldTypeKind, values?: FieldTypeKind, children?: (FieldIR | ParamIR)[]): string {
  switch (type) {
    case 'string': return 'z.string()';
    case 'number': return 'z.number()';
    case 'boolean': return 'z.boolean()';
    case 'array': {
      const itemZod = items ? primitiveToZod(items) : 'z.unknown()';
      // If items is 'object' and we have children, use z.object for items
      if (items === 'object' && children && children.length > 0) {
        const fields = children.map(c => `${c.name}: ${'type' in c && 'description' in c ? fieldToZod(c as FieldIR) : paramToZod(c as ParamIR)}`);
        return `z.array(z.object({ ${fields.join(', ')} }))`;
      }
      return `z.array(${itemZod})`;
    }
    case 'object': {
      if (children && children.length > 0) {
        const fields = children.map(c => `${c.name}: ${'description' in c && typeof (c as any).description === 'string' ? fieldToZod(c as FieldIR) : paramToZod(c as ParamIR)}`);
        return `z.object({ ${fields.join(', ')} })`;
      }
      return 'z.object({})';
    }
    case 'record': {
      const valueZod = values ? primitiveToZod(values) : 'z.unknown()';
      return `z.record(z.string(), ${valueZod})`;
    }
    default: return 'z.unknown()';
  }
}

function primitiveToZod(type: FieldTypeKind): string {
  switch (type) {
    case 'string': return 'z.string()';
    case 'number': return 'z.number()';
    case 'boolean': return 'z.boolean()';
    default: return 'z.unknown()';
  }
}

function applyValidation(code: string, type: FieldTypeKind, v?: ValidateIR): string {
  if (!v) return code;

  // String constraints
  if (type === 'string') {
    if (v.minLength != null) code += `.min(${v.minLength})`;
    if (v.maxLength != null) code += `.max(${v.maxLength})`;
    if (v.pattern) code += `.regex(/${v.pattern}/)`;
    if (v.format === 'email') code += '.email()';
    if (v.format === 'url') code += '.url()';
    if (v.format === 'uuid') code += '.uuid()';
    if (v.format === 'datetime') code += '.datetime()';
    if (v.format === 'date') code += '.date()';
  }

  // Number constraints
  if (type === 'number') {
    if (v.integer) code += '.int()';
    if (v.min != null) code += `.min(${v.min})`;
    if (v.max != null) code += `.max(${v.max})`;
  }

  // Array constraints
  if (type === 'array') {
    if (v.minItems != null) code += `.min(${v.minItems})`;
    if (v.maxItems != null) code += `.max(${v.maxItems})`;
  }

  // Enum (replaces base type)
  if (v.enum && v.enum.length > 0) {
    return `z.enum([${v.enum.map(e => `'${esc(e)}'`).join(', ')}])`;
  }

  return code;
}

function toolInputToZod(tool: ToolIR): string {
  if (tool.input.length === 0) return 'z.object({})';
  const fields = tool.input.map(p => `${p.name}: ${paramToZod(p)}`);
  return `z.object({ ${fields.join(', ')} })`;
}

function toolOutputToZod(tool: ToolIR): string {
  if (!tool.output) return 'z.void()';
  const { type, items, params } = tool.output;
  return baseTypeToZod(type, items, undefined, params);
}

// ─── Helpers ────────────────────────────────────────────

function toKebab(name: string): string {
  return name.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();
}

function esc(s: string): string {
  return s.replace(/'/g, "\\'");
}
