/**
 * Entity tree generator.
 *
 * Walks the GraphIR from the root entity and produces the EntityTree
 * constant that the runtime consumes. Output shape matches
 * sdk/src/entity/wrappers/types.ts EntityNode interface.
 */

import type { GraphIR, EntityIR, FieldIR, ParamIR, FieldTypeKind } from '../ir.js';

// Matches sdk/src/entity/wrappers/types.ts
interface EntityNode {
  id: string;
  type: string;
  className: string;
  describe?: string;
  infra: { remote?: string };
  state: Array<{ name: string; id: string }>;
  refs: Array<{ propertyName: string; targetEntityType: string; id: string }>;
  components: Array<{ id: string; propertyName: string; entityType: string; entity?: EntityNode }>;
  streams: Array<{ propertyName: string; id: string }>;
  methods: Array<{ methodName: string; eventName: string; id: string; description?: string; inputSchema?: MethodInputSchema }>;
  hooks: Array<{ methodName: string; hookTypeName: string; runnerExport?: string; inProcess: boolean; id: string }>;
}

interface MethodInputSchema {
  fields: MethodInputField[];
}

interface MethodInputField {
  name: string;
  type: FieldType;
  optional: boolean;
}

type FieldType =
  | 'string' | 'number' | 'boolean'
  | { kind: 'array'; element: FieldType }
  | { kind: 'enum'; values: Array<string | number> }
  | { kind: 'object'; fields: MethodInputField[] };

export function generateTree(graph: GraphIR): string {
  const entityMap = new Map(graph.entities.map(e => [e.name, e]));

  // Find root entity
  const rootName = graph.root ?? graph.entities[0]?.name;
  if (!rootName) throw new Error('No entities defined in graph');

  const rootEntity = entityMap.get(rootName);
  if (!rootEntity) throw new Error(`Root entity "${rootName}" not found`);

  const rootType = toKebab(rootName);
  const tree = buildNode(rootEntity, rootType, entityMap);

  const lines: string[] = [];
  lines.push('// AUTO-GENERATED by @interactkit/cli — do not edit');
  lines.push('');
  lines.push(`export const entityTree = ${serialize(tree, 0)} as const;`);
  lines.push('');
  return lines.join('\n');
}

function buildNode(entity: EntityIR, pathId: string, entityMap: Map<string, EntityIR>): EntityNode {
  const entityType = toKebab(entity.name);

  return {
    id: pathId,
    type: entityType,
    className: entity.name,
    describe: entity.describe,
    infra: { remote: entity.remote || undefined },
    state: [
      ...entity.state.map(f => ({
        name: f.name,
        id: `${pathId}.${f.name}`,
        default: f.default != null ? parseDefault(f)
          : f.type === 'array' ? []
          : f.type === 'record' ? {}
          : f.type === 'number' ? 0
          : f.type === 'boolean' ? false
          : f.type === 'string' ? ''
          : undefined,
      })),
      ...entity.fieldGroups.map(fg => ({
        name: fg.name,
        id: `${pathId}.${fg.name}`,
        default: [],
      })),
    ],
    refs: entity.refs.map(r => ({
      propertyName: r.name,
      targetEntityType: toKebab(r.entity),
      id: `${pathId}.${r.name}`,
    })),
    components: entity.components.map(c => {
      const childEntity = entityMap.get(c.entity);
      const childId = `${pathId}.${c.name}`;
      return {
        id: childId,
        propertyName: c.name,
        entityType: toKebab(c.entity),
        entity: childEntity ? buildNode(childEntity, childId, entityMap) : undefined,
      };
    }),
    streams: entity.streams.map(s => ({
      propertyName: s.name,
      id: `${pathId}.${s.name}`,
    })),
    methods: entity.tools.map(t => ({
      methodName: t.name,
      eventName: `${entityType}.${t.name}`,
      id: `${pathId}.${t.name}`,
      description: t.description,
      inputSchema: t.input.length > 0 ? { fields: t.input.map(paramToField) } : undefined,
      ...((t as any).auto ? { auto: (t as any).auto, on: (t as any).on, ...((t as any).key ? { key: (t as any).key } : {}) } : {}),
    })),
    // No hooks in v4 — empty array for compat
    hooks: [],
    // LLM executor config (for runtime to create LangChain model)
    ...(entity.executor ? {
      executor: {
        provider: entity.executor.provider,
        model: entity.executor.model,
        ...(entity.executor.temperature != null ? { temperature: entity.executor.temperature } : {}),
        ...(entity.executor.maxTokens != null ? { maxTokens: entity.executor.maxTokens } : {}),
      },
    } : {}),
  };
}

function paramToField(param: ParamIR): MethodInputField {
  return {
    name: param.name,
    type: paramToFieldType(param),
    optional: param.optional,
  };
}

function paramToFieldType(param: ParamIR): FieldType {
  switch (param.type) {
    case 'string': return 'string';
    case 'number': return 'number';
    case 'boolean': return 'boolean';
    case 'array': return { kind: 'array', element: fieldTypeKindToFieldType(param.items ?? 'string') };
    case 'object': return { kind: 'object', fields: param.children.map(paramToField) };
    default: return 'string';
  }
}

function parseDefault(field: FieldIR): any {
  if (field.default == null) return undefined;
  if (field.type === 'number') return Number(field.default);
  if (field.type === 'boolean') return field.default === 'true';
  if (field.type === 'array') return [];
  if (field.type === 'record' || field.type === 'object') {
    try { return JSON.parse(field.default); } catch { return {}; }
  }
  return field.default;
}

function fieldTypeKindToFieldType(kind: FieldTypeKind): FieldType {
  if (kind === 'string' || kind === 'number' || kind === 'boolean') return kind;
  return 'string'; // fallback for complex nested types in arrays
}

function toKebab(name: string): string {
  return name.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();
}

// ─── Serializer ─────────────────────────────────────────

function serialize(obj: any, depth: number): string {
  const indent = '  '.repeat(depth);
  const inner = '  '.repeat(depth + 1);

  if (obj === undefined) return 'undefined';
  if (obj === null) return 'null';
  if (typeof obj === 'string') return JSON.stringify(obj);
  if (typeof obj === 'number' || typeof obj === 'boolean') return String(obj);

  if (Array.isArray(obj)) {
    if (obj.length === 0) return '[]';
    const items = obj.map(item => `${inner}${serialize(item, depth + 1)}`);
    return `[\n${items.join(',\n')}\n${indent}]`;
  }

  const entries = Object.entries(obj).filter(([_, v]) => v !== undefined);
  if (entries.length === 0) return '{}';
  const props = entries.map(([k, v]) => `${inner}${k}: ${serialize(v, depth + 1)}`);
  return `{\n${props.join(',\n')}\n${indent}}`;
}
