/**
 * Types generator — produces all TS interfaces.
 *
 * Generates: state interfaces, tool input/output types, entity context types,
 * proxy interfaces, and typed addHandler/on overloads.
 */

import type { GraphIR, EntityIR, FieldIR, FieldGroupIR, ParamIR, FieldTypeKind, ToolIR, RefIR } from '../ir.js';

export function generateTypes(graph: GraphIR): string {
  const lines: string[] = [];
  const entityMap = new Map(graph.entities.map(e => [e.name, e]));

  lines.push('// AUTO-GENERATED by @interactkit/cli — do not edit');
  lines.push("import type { Entity } from '@interactkit/sdk';");
  lines.push('');

  // ─── Per-entity types ─────────────────────────────────

  for (const entity of graph.entities) {
    const name = entity.name;

    // State interface
    const hasState = entity.state.length > 0 || entity.fieldGroups.length > 0;
    if (hasState) {
      // FieldGroup item interfaces
      for (const fg of entity.fieldGroups) {
        lines.push(`export interface ${name}${pascal(fg.name)}Item {`);
        lines.push(`  ${fg.key}: string;`);
        for (const field of fg.fields) {
          lines.push(`  ${field.name}${field.optional ? '?' : ''}: ${fieldToTS(field)};`);
        }
        lines.push('}');
        lines.push('');
      }

      lines.push(`export interface ${name}State {`);
      for (const field of entity.state) {
        lines.push(`  ${field.name}${field.optional ? '?' : ''}: ${fieldToTS(field)};`);
      }
      for (const fg of entity.fieldGroups) {
        lines.push(`  ${fg.name}: ${name}${pascal(fg.name)}Item[];`);
      }
      lines.push('}');
      lines.push('');

      // Nested object types for state fields
      for (const field of entity.state) {
        emitNestedTypes(name, field, lines);
      }
    }

    // Tool input/output interfaces
    for (const tool of entity.tools) {
      if (tool.input.length > 0) {
        lines.push(`export interface ${name}${pascal(tool.name)}Input {`);
        for (const p of tool.input) {
          lines.push(`  ${p.name}${p.optional ? '?' : ''}: ${paramToTS(p)};`);
        }
        lines.push('}');
        lines.push('');
      }

      if (tool.output && tool.output.params.length > 0 && tool.output.type === 'object') {
        lines.push(`export interface ${name}${pascal(tool.name)}Output {`);
        for (const p of tool.output.params) {
          lines.push(`  ${p.name}${p.optional ? '?' : ''}: ${paramToTS(p)};`);
        }
        lines.push('}');
        lines.push('');
      }
    }

    // Entity context type (what handlers receive)
    lines.push(`export interface ${name}Entity extends Entity {`);
    if (hasState) {
      lines.push(`  state: ${name}State;`);
    } else {
      lines.push('  state: Record<string, never>;');
    }
    if (entity.refs.length > 0) {
      lines.push('  refs: {');
      for (const ref of entity.refs) {
        const refEntity = entityMap.get(ref.entity);
        if (refEntity) {
          // Use RefProxy (peerVisible only) if it exists, otherwise full Proxy
          const refHasPeerProxy = refEntity.tools.some(t => t.peerVisible) || refEntity.type === 'llm';
          const proxyType = refHasPeerProxy ? `${ref.entity}RefProxy` : `${ref.entity}Proxy`;
          lines.push(`    ${ref.name}: ${proxyType};`);
        }
      }
      lines.push('  };');
    }
    if (entity.components.length > 0) {
      lines.push('  components: {');
      for (const comp of entity.components) {
        lines.push(`    ${comp.name}: ${comp.entity}Proxy;`);
      }
      lines.push('  };');
    }
    if (entity.secrets.length > 0) {
      lines.push('  secrets: {');
      for (const s of entity.secrets) {
        lines.push(`    ${s.name}: string;`);
      }
      lines.push('  };');
    }
    if (entity.streams.length > 0) {
      lines.push('  streams: {');
      for (const s of entity.streams) {
        lines.push(`    ${s.name}: { emit(data: ${streamPayloadType(s)}): void };`);
      }
      lines.push('  };');
    }
    lines.push('}');
    lines.push('');

    // Proxy interface (typed method signatures — all tools)
    lines.push(`export interface ${name}Proxy {`);
    for (const tool of entity.tools) {
      const inputType = tool.input.length > 0 ? `${name}${pascal(tool.name)}Input` : '';
      const outputType = toolOutputTS(entity, tool);
      const params = inputType ? `input: ${inputType}` : '';
      lines.push(`  ${tool.name}(${params}): Promise<${outputType}>;`);
    }
    // LLM entities get invoke()
    if (entity.type === 'llm') {
      lines.push('  invoke(input: { message: string }): Promise<string>;');
    }
    // Components as nested proxy accessors
    for (const comp of entity.components) {
      lines.push(`  ${comp.name}: ${comp.entity}Proxy;`);
    }
    lines.push('}');
    lines.push('');

    // RefProxy interface (only peerVisible tools — what refs/siblings see)
    const peerTools = entity.tools.filter(t => t.peerVisible);
    const hasPeerTools = peerTools.length > 0 || entity.type === 'llm';
    if (hasPeerTools) {
      lines.push(`export interface ${name}RefProxy {`);
      for (const tool of peerTools) {
        const inputType = tool.input.length > 0 ? `${name}${pascal(tool.name)}Input` : '';
        const outputType = toolOutputTS(entity, tool);
        const params = inputType ? `input: ${inputType}` : '';
        lines.push(`  ${tool.name}(${params}): Promise<${outputType}>;`);
      }
      if (entity.type === 'llm') {
        lines.push('  invoke(input: { message: string }): Promise<string>;');
      }
      lines.push('}');
      lines.push('');
    }
  }

  // ─── Fluent handler interfaces (graph.EntityName.handle) ─

  for (const entity of graph.entities) {
    const name = entity.name;
    const ctxType = `${name}Entity`;

    lines.push(`export interface ${name}HandleBuilder {`);
    for (const tool of entity.tools) {
      const inputType = tool.input.length > 0 ? `${name}${pascal(tool.name)}Input` : '';
      const outputType = toolOutputTS(entity, tool);
      const fnParams = inputType ? `entity: ${ctxType}, input: ${inputType}` : `entity: ${ctxType}`;
      const returnType = outputType === 'void' ? 'Promise<void> | void' : `Promise<${outputType}>`;
      lines.push(`  ${tool.name}(fn: (${fnParams}) => ${returnType}): ${name}HandleBuilder;`);
    }
    lines.push(`  describe(fn: (entity: ${ctxType}) => string): ${name}HandleBuilder;`);
    lines.push(`  init(fn: (entity: ${ctxType}) => Promise<void> | void): ${name}HandleBuilder;`);
    lines.push('}');
    lines.push('');
  }

  // ─── addHandler overloads ─────────────────────────────

  lines.push('export interface AddHandlerOverloads {');
  for (const entity of graph.entities) {
    const name = entity.name;
    const entityType = toKebab(name);
    const ctxType = `${name}Entity`;

    // Tool handlers
    for (const tool of entity.tools) {
      const inputType = tool.input.length > 0 ? `${name}${pascal(tool.name)}Input` : '';
      const outputType = toolOutputTS(entity, tool);
      const fnParams = inputType ? `entity: ${ctxType}, input: ${inputType}` : `entity: ${ctxType}`;
      const returnType = outputType === 'void' ? 'Promise<void> | void' : `Promise<${outputType}>`;
      lines.push(`  (entity: '${entityType}', method: '${tool.name}', fn: (${fnParams}) => ${returnType}): void;`);
    }

    // describe handler
    lines.push(`  (entity: '${entityType}', method: 'describe', fn: (entity: ${ctxType}) => string): void;`);

    // init handler
    lines.push(`  (entity: '${entityType}', method: 'init', fn: (entity: ${ctxType}) => Promise<void> | void): void;`);
  }
  lines.push('}');
  lines.push('');

  // ─── on overloads ─────────────────────────────────────

  lines.push('export interface OnOverloads {');
  for (const entity of graph.entities) {
    const name = entity.name;
    const entityType = toKebab(name);

    for (const tool of entity.tools) {
      const inputType = tool.input.length > 0 ? `${name}${pascal(tool.name)}Input` : 'void';
      const outputType = toolOutputTS(entity, tool);
      lines.push(`  (entity: '${entityType}', method: '${tool.name}', fn: (input: ${inputType}, result: ${outputType}) => void): void;`);
    }
  }
  lines.push('}');
  lines.push('');

  // ─── HandlersConfig (for graph.configure({ handlers })) ─

  lines.push('/** Handler methods for a single entity type. All optional — unhandled tools use auto/LLM fallback. */');
  for (const entity of graph.entities) {
    const name = entity.name;
    const ctxType = `${name}Entity`;

    lines.push(`export interface ${name}Handlers {`);
    for (const tool of entity.tools) {
      const inputType = tool.input.length > 0 ? `${name}${pascal(tool.name)}Input` : '';
      const outputType = toolOutputTS(entity, tool);
      const fnParams = inputType ? `entity: ${ctxType}, input: ${inputType}` : `entity: ${ctxType}`;
      const returnType = outputType === 'void' ? 'Promise<void> | void' : `Promise<${outputType}>`;
      lines.push(`  ${tool.name}?: (${fnParams}) => ${returnType};`);
    }
    lines.push(`  describe?: (entity: ${ctxType}) => string;`);
    lines.push(`  init?: (entity: ${ctxType}) => Promise<void> | void;`);
    lines.push('}');
    lines.push('');
  }

  lines.push('/** Handlers keyed by entity type (e.g. "Phone") or path override (e.g. "john.phone"). */');
  lines.push('export type HandlersConfig = {');
  for (const entity of graph.entities) {
    const entityType = toKebab(entity.name);
    lines.push(`  '${entity.name}'?: ${entity.name}Handlers;`);
    lines.push(`  '${entityType}'?: ${entity.name}Handlers;`);
  }
  lines.push('} & {');
  lines.push('  /** Path-based overrides (e.g. "john.phone") */');
  lines.push('  [path: string]: Record<string, Function> | undefined;');
  lines.push('};');
  lines.push('');

  return lines.join('\n');
}

// ─── TS type generation ─────────────────────────────────

function fieldToTS(field: FieldIR): string {
  // Enum validation narrows string to union literal
  if (field.type === 'string' && field.validate?.enum && field.validate.enum.length > 0) {
    return field.validate.enum.map(e => `'${e}'`).join(' | ');
  }
  return fieldTypeToTS(field.type, field.items, field.values, field.children, field.name);
}

function paramToTS(param: ParamIR): string {
  // Enum validation narrows string to union literal
  if (param.type === 'string' && param.validate?.enum && param.validate.enum.length > 0) {
    return param.validate.enum.map(e => `'${e}'`).join(' | ');
  }
  return fieldTypeToTS(param.type, param.items, param.values, param.children, param.name);
}

function fieldTypeToTS(type: FieldTypeKind, items?: FieldTypeKind, values?: FieldTypeKind, children?: (FieldIR | ParamIR)[], _name?: string): string {
  switch (type) {
    case 'string': return 'string';
    case 'number': return 'number';
    case 'boolean': return 'boolean';
    case 'array': {
      if (items === 'object' && children && children.length > 0) {
        const fields = children.map(c => `${c.name}${c.optional ? '?' : ''}: ${'description' in c ? fieldToTS(c as FieldIR) : paramToTS(c as ParamIR)}`);
        return `Array<{ ${fields.join('; ')} }>`;
      }
      return `${primitiveToTS(items ?? 'string')}[]`;
    }
    case 'object': {
      if (children && children.length > 0) {
        const fields = children.map(c => `${c.name}${c.optional ? '?' : ''}: ${'description' in c ? fieldToTS(c as FieldIR) : paramToTS(c as ParamIR)}`);
        return `{ ${fields.join('; ')} }`;
      }
      return 'Record<string, unknown>';
    }
    case 'record': return `Record<string, ${primitiveToTS(values ?? 'string')}>`;
    default: return 'unknown';
  }
}

function primitiveToTS(type: FieldTypeKind): string {
  if (type === 'string' || type === 'number' || type === 'boolean') return type;
  return 'unknown';
}

function toolOutputTS(entity: EntityIR, tool: ToolIR): string {
  if (!tool.output) return 'void';
  const { type, items, params } = tool.output;

  // void output
  if ((type as string) === 'void') return 'void';

  // Named output interface for non-autotool object returns
  if (type === 'object' && params.length > 0 && !tool.auto) {
    return `${entity.name}${pascal(tool.name)}Output`;
  }

  // Autotool: reuse named item type for list/search/read returns
  if (tool.auto) {
    const autoTool = tool as ToolIR & { on?: string };
    const fgName = autoTool.on;
    if (fgName) {
      const itemType = `${entity.name}${pascal(fgName)}Item`;
      if (type === 'array' && items === 'object') {
        return `${itemType}[]`;
      }
      if (type === 'object' && params.length > 0) {
        return itemType;
      }
    }
  }

  return fieldTypeToTS(type, items, undefined, params);
}

function streamPayloadType(stream: { type: FieldTypeKind; params: ParamIR[] }): string {
  if (stream.type === 'object' && stream.params.length > 0) {
    const fields = stream.params.map(p => `${p.name}: ${paramToTS(p)}`);
    return `{ ${fields.join('; ')} }`;
  }
  return primitiveToTS(stream.type);
}

function emitNestedTypes(entityName: string, field: FieldIR, lines: string[]): void {
  // If array of objects with named children, emit a named interface
  if (field.type === 'array' && field.items === 'object' && field.children.length > 0) {
    const typeName = `${entityName}${pascal(field.name)}Item`;
    lines.push(`export interface ${typeName} {`);
    for (const child of field.children) {
      lines.push(`  ${child.name}${child.optional ? '?' : ''}: ${fieldToTS(child)};`);
    }
    lines.push('}');
    lines.push('');
  }

  for (const child of field.children) {
    emitNestedTypes(entityName, child, lines);
  }
}

// ─── Helpers ────────────────────────────────────────────

function pascal(s: string): string {
  return s[0].toUpperCase() + s.slice(1);
}

function toKebab(name: string): string {
  return name.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();
}
