import { resolve } from 'node:path';
import { mkdirSync, writeFileSync, cpSync, existsSync } from 'node:fs';
import { execSync } from 'node:child_process';
import { Project } from 'ts-morph';
import { extractEntities } from '../codegen/extract/index.js';
import { emit } from '../codegen/emit/index.js';
import { generateDeploymentPlan } from '../codegen/deploy/index.js';

interface Flags {
  project: string;
  outDir: string;
}

export async function buildCommand(flags: Flags) {
  const cwd = process.cwd();
  const projectPath = resolve(cwd, flags.project);
  const generatedDir = resolve(cwd, '.interactkit/generated');
  const buildDir = resolve(cwd, '.interactkit/build');

  // Step 1: Codegen → .interactkit/generated/type-registry.ts
  console.log('▸ codegen');
  const project = new Project({ tsConfigFilePath: projectPath });
  const entities = extractEntities(project);

  mkdirSync(generatedDir, { recursive: true });

  if (entities.length === 0) {
    console.log('  No @Entity classes found.');
    writeFileSync(resolve(generatedDir, 'type-registry.ts'), 'export const Registry = { entities: {} } as const;\n');
  } else {
    const code = emit(entities);
    writeFileSync(resolve(generatedDir, 'type-registry.ts'), code, 'utf-8');

    const methodCount = entities.reduce((sum, e) => sum + e.methods.length, 0);
    const hookCount = entities.reduce((sum, e) => sum + e.hooks.length, 0);
    console.log(`  ${entities.length} entities, ${methodCount} methods, ${hookCount} hooks`);

    // Generate deployment plan
    const plan = generateDeploymentPlan(entities);
    writeFileSync(resolve(generatedDir, 'deployment.json'), JSON.stringify(plan, null, 2), 'utf-8');
    console.log(`  ${plan.units.length} deployment units, ${plan.connections.length} cross-unit connections`);
  }

  // Step 2: Generate _bootstrap.ts — sets registry then re-exports user entry
  const bootstrapCode = [
    '// AUTO-GENERATED by interactkit build — do not edit',
    "import 'reflect-metadata';",
    "import { setRegistry } from '@interactkit/sdk';",
    "import { Registry } from './type-registry.js';",
    'setRegistry(Registry);',
    "export * from './index.js';",
    '',
  ].join('\n');
  writeFileSync(resolve(generatedDir, '_entry.ts'), bootstrapCode, 'utf-8');

  // Step 3: TypeScript compilation → .interactkit/build/
  console.log('▸ tsc');
  mkdirSync(buildDir, { recursive: true });
  try {
    execSync(`npx tsc --outDir "${buildDir}"`, { stdio: 'inherit', cwd });
  } catch {
    process.exit(1);
  }

  // Step 4: Merge generated output into src output so rootDirs imports resolve at runtime
  const generatedBuildDir = resolve(buildDir, '.interactkit/generated');
  const srcBuildDir = resolve(buildDir, 'src');
  if (existsSync(generatedBuildDir) && existsSync(srcBuildDir)) {
    cpSync(generatedBuildDir, srcBuildDir, { recursive: true, force: true });
  }

  console.log('▸ done');
}
