import { resolve } from 'node:path';
import { mkdirSync, writeFileSync, cpSync, existsSync } from 'node:fs';
import { execSync } from 'node:child_process';
import { Project } from 'ts-morph';
import { extractEntities } from '../codegen/extract/index.js';
import { emit } from '../codegen/emit/index.js';
import { generateDeploymentPlan } from '../codegen/deploy/index.js';

interface Flags {
  project: string;
  outDir: string;
  root?: string;
  dev?: boolean;
}

export async function buildCommand(flags: Flags) {
  const cwd = process.cwd();
  const projectPath = resolve(cwd, flags.project);
  const generatedDir = resolve(cwd, '.interactkit/generated');
  const buildDir = resolve(cwd, '.interactkit/build');

  // Step 1: Codegen → .interactkit/generated/type-registry.ts
  console.log('▸ codegen');
  const project = new Project({ tsConfigFilePath: projectPath });
  const entities = extractEntities(project);

  mkdirSync(generatedDir, { recursive: true });

  if (entities.length === 0) {
    console.log('  No @Entity classes found.');
    writeFileSync(resolve(generatedDir, 'type-registry.ts'), 'export const Registry = { entities: {} } as const;\n');
  } else {
    const code = emit(entities);
    writeFileSync(resolve(generatedDir, 'type-registry.ts'), code, 'utf-8');

    const methodCount = entities.reduce((sum, e) => sum + e.methods.length, 0);
    const hookCount = entities.reduce((sum, e) => sum + e.hooks.length, 0);
    console.log(`  ${entities.length} entities, ${methodCount} methods, ${hookCount} hooks`);

    // Generate deployment plan
    const plan = generateDeploymentPlan(entities);
    writeFileSync(resolve(generatedDir, 'deployment.json'), JSON.stringify(plan, null, 2), 'utf-8');
    console.log(`  ${plan.units.length} deployment units, ${plan.connections.length} cross-unit connections`);
  }

  // Step 2: Generate _entry.ts — sets registry, boots root entity
  const entryLines = [
    '// AUTO-GENERATED by interactkit build — do not edit',
    "import 'dotenv/config';",
    "import 'reflect-metadata';",
    flags.dev
      ? "import { setRegistry, boot, DevLogAdapter } from '@interactkit/sdk';"
      : "import { setRegistry, boot } from '@interactkit/sdk';",
    "import { Registry } from './type-registry.js';",
    'setRegistry(Registry);',
  ];

  if (flags.root) {
    // Parse --root=path/to/file:ExportName
    const colonIdx = flags.root.lastIndexOf(':');
    if (colonIdx === -1) {
      console.error('--root must be in the format path/to/file:ExportName (e.g. src/entities/agent:Agent)');
      process.exit(1);
    }
    const rootFile = flags.root.slice(0, colonIdx);
    const rootExport = flags.root.slice(colonIdx + 1);

    // Import path relative to the virtual merged root (rootDirs merges src/ and .interactkit/generated/)
    const importPath = `./${rootFile.replace(/^src\//, '')}.js`;

    entryLines.push(
      `import { ${rootExport} } from '${importPath}';`,
      '',
      flags.dev
        ? 'const ctx = await boot(' + rootExport + ', { logger: new DevLogAdapter() });'
        : 'const ctx = await boot(' + rootExport + ');',
      'console.log(`▸ booted ${ctx.entities.size} entities`);',
      '',
      '// Graceful shutdown',
      "process.on('SIGINT', async () => {",
      '  await ctx.shutdown();',
      '  process.exit(0);',
      '});',
    );
  } else {
    // No --root: just export the registry (legacy / test mode)
    entryLines.push("export * from './index.js';");
  }

  entryLines.push('');
  writeFileSync(resolve(generatedDir, '_entry.ts'), entryLines.join('\n'), 'utf-8');

  // Step 3: TypeScript compilation → .interactkit/build/
  console.log('▸ tsc');
  mkdirSync(buildDir, { recursive: true });
  try {
    execSync(`npx tsc --outDir "${buildDir}"`, { stdio: 'inherit', cwd });
  } catch {
    process.exit(1);
  }

  // Step 4: Merge generated output into src output so rootDirs imports resolve at runtime
  const generatedBuildDir = resolve(buildDir, '.interactkit/generated');
  const srcBuildDir = resolve(buildDir, 'src');
  if (existsSync(generatedBuildDir) && existsSync(srcBuildDir)) {
    cpSync(generatedBuildDir, srcBuildDir, { recursive: true, force: true });
  }

  console.log('▸ done');
}
