import { resolve } from 'node:path';
import { mkdirSync, writeFileSync, cpSync, existsSync } from 'node:fs';
import { execSync } from 'node:child_process';
import { Project } from 'ts-morph';
import { extractEntities } from '../codegen/extract/index.js';
import { emit } from '../codegen/emit/index.js';
import { generateDeploymentPlan } from '../codegen/deploy/index.js';

interface Flags {
  project: string;
  outDir: string;
  root?: string;
  dev?: boolean;
}

export async function buildCommand(flags: Flags) {
  const cwd = process.cwd();
  const projectPath = resolve(cwd, flags.project);
  const generatedDir = resolve(cwd, '.interactkit/generated');
  const buildDir = resolve(cwd, '.interactkit/build');

  // Step 1: Codegen → .interactkit/generated/type-registry.ts
  console.log('▸ codegen');
  const project = new Project({ tsConfigFilePath: projectPath });
  const entities = extractEntities(project);

  mkdirSync(generatedDir, { recursive: true });

  if (entities.length === 0) {
    console.log('  No @Entity classes found.');
    writeFileSync(resolve(generatedDir, 'type-registry.ts'), 'export const Registry = { entities: {} } as const;\n');
  } else {
    const code = emit(entities);
    writeFileSync(resolve(generatedDir, 'type-registry.ts'), code, 'utf-8');

    const methodCount = entities.reduce((sum, e) => sum + e.methods.length, 0);
    const hookCount = entities.reduce((sum, e) => sum + e.hooks.length, 0);
    console.log(`  ${entities.length} entities, ${methodCount} methods, ${hookCount} hooks`);

    // Generate deployment plan
    const plan = generateDeploymentPlan(entities);
    writeFileSync(resolve(generatedDir, 'deployment.json'), JSON.stringify(plan, null, 2), 'utf-8');
    console.log(`  ${plan.units.length} deployment units, ${plan.connections.length} cross-unit connections`);
  }

  // Step 2: Generate _entry.ts — sets registry, boots root entity
  const entryLines = [
    '// AUTO-GENERATED by interactkit build — do not edit',
    "import 'dotenv/config';",
    "import 'reflect-metadata';",
    flags.dev
      ? "import { setRegistry, boot, DevLogAdapter } from '@interactkit/sdk';"
      : "import { setRegistry, boot } from '@interactkit/sdk';",
    "import { Registry } from './type-registry.js';",
    'setRegistry(Registry);',
  ];

  if (flags.root) {
    // Parse --root=path/to/file:ExportName
    const colonIdx = flags.root.lastIndexOf(':');
    if (colonIdx === -1) {
      console.error('--root must be in the format path/to/file:ExportName (e.g. src/entities/agent:Agent)');
      process.exit(1);
    }
    const rootFile = flags.root.slice(0, colonIdx);
    const rootExport = flags.root.slice(colonIdx + 1);

    // Import path relative to the virtual merged root (rootDirs merges src/ and .interactkit/generated/)
    const importPath = `./${rootFile.replace(/^src\//, '')}.js`;

    entryLines.push(
      `import { ${rootExport} } from '${importPath}';`,
      '',
      flags.dev
        ? 'const ctx = await boot(' + rootExport + ', { logger: new DevLogAdapter() });'
        : 'const ctx = await boot(' + rootExport + ');',
      'console.log(`▸ booted ${ctx.entities.size} entities`);',
      '',
      '// Graceful shutdown',
      "process.on('SIGINT', async () => {",
      '  await ctx.shutdown();',
      '  process.exit(0);',
      '});',
    );
  } else {
    // No --root: just export the registry (legacy / test mode)
    entryLines.push("export * from './index.js';");
  }

  entryLines.push('');
  writeFileSync(resolve(generatedDir, '_entry.ts'), entryLines.join('\n'), 'utf-8');

  // Step 2b: Generate _hooks.ts — standalone hook server entrypoint
  // Only includes hooks that are NOT inProcess (those run directly in the entity server)
  const remoteHooks = entities.flatMap(e =>
    e.hooks.filter(h => !h.inProcess).map(h => ({ entityType: e.type, ...h }))
  );

  if (remoteHooks.length === 0) {
    writeFileSync(resolve(generatedDir, '_hooks.ts'), '// No remote hooks — all hooks run in-process.\n');
  } else {
    const hookLines = [
      '// AUTO-GENERATED by interactkit build — do not edit',
      '// Hook server: runs hook runners and enqueues events for entities to consume.',
      '// inProcess hooks (e.g. Init) are excluded — they run directly in the entity server.',
      "import 'dotenv/config';",
      "import 'reflect-metadata';",
      "import { HookExecutor } from '@interactkit/sdk';",
    ];

    // Collect imports by source package
    const imports = new Map<string, Set<string>>();
    for (const hook of remoteHooks) {
      const pkg = hook.sourcePackage ?? '@interactkit/sdk';
      if (!imports.has(pkg)) imports.set(pkg, new Set());
      const ns = hook.runnerExport?.split('.')[0];
      if (ns) imports.get(pkg)!.add(ns);
    }
    for (const [pkg, names] of imports) {
      hookLines.push(`import { ${[...names].join(', ')} } from '${pkg}';`);
    }

    // Determine pubsub adapter from root entity
    const rootEntity = entities.find(e => !entities.some(p => p.components.some(c => c.entityType === e.type)));
    const pubsubAdapter = rootEntity?.infra.pubsub ?? 'InProcessBusAdapter';
    hookLines.push(`import { ${pubsubAdapter} } from '@interactkit/sdk';`);

    hookLines.push(
      '',
      `const pubsub = new ${pubsubAdapter}();`,
      'const executor = new HookExecutor(pubsub);',
      '',
    );

    for (const hook of remoteHooks) {
      const runner = hook.runnerExport ?? `${hook.hookTypeName}.Runner()`;
      hookLines.push(`await executor.startRunner('${hook.entityType}', '${hook.methodName}', ${runner});`);
    }

    hookLines.push(
      '',
      `console.log('▸ hook server started (${remoteHooks.length} runners)');`,
      '',
      "process.on('SIGINT', async () => {",
      '  await executor.stopAll();',
      '  process.exit(0);',
      '});',
      '',
    );

    writeFileSync(resolve(generatedDir, '_hooks.ts'), hookLines.join('\n'), 'utf-8');
  }

  // Step 2c: Generate per-unit entrypoints from deployment plan
  if (entities.length > 0) {
    const plan = generateDeploymentPlan(entities);
    const entityMap = new Map(entities.map(e => [e.type, e]));

    // Build parent map to find each unit's root entity
    const parentOf = new Map<string, string>();
    for (const entity of entities) {
      for (const comp of entity.components) {
        parentOf.set(comp.entityType, entity.type);
      }
    }

    if (plan.units.length > 1) {
      for (const unit of plan.units) {
        const unitEntities = unit.entities.map(t => entityMap.get(t)!).filter(Boolean);

        // Find the root of this unit (entity with no parent within the unit)
        const unitTypeSet = new Set(unit.entities);
        const unitRoot = unitEntities.find(e => {
          const parent = parentOf.get(e.type);
          return !parent || !unitTypeSet.has(parent);
        });
        if (!unitRoot) continue;

        // Build import lines for each entity in this unit
        const importLines: string[] = [];
        for (const entity of unitEntities) {
          // sourceFile is absolute — extract the part after src/
          const srcIdx = entity.sourceFile.indexOf('/src/');
          const relPath = srcIdx >= 0 ? entity.sourceFile.slice(srcIdx + 5) : entity.sourceFile;
          const importPath = `./${relPath.replace(/\.ts$/, '')}.js`;
          importLines.push(`import { ${entity.className} } from '${importPath}';`);
        }

        // Determine pubsub for this unit
        const unitPubsub = unit.busAdapter !== 'InProcessBusAdapter' ? unit.busAdapter : undefined;
        const sdkImports = ['setRegistry', 'Runtime'];
        if (flags.dev) sdkImports.push('DevLogAdapter');
        if (unitPubsub) sdkImports.push(unitPubsub);

        const addLines = unitEntities.map(e => `await runtime.add(${e.className});`);

        const unitLines = [
          `// AUTO-GENERATED by interactkit build — do not edit`,
          `// Deployment unit: ${unit.name}`,
          `// Entities: ${unit.entities.join(', ')}`,
          `// Scalable: ${unit.scalable}`,
          `// Bus: ${unit.busAdapter}`,
          "import 'dotenv/config';",
          "import 'reflect-metadata';",
          `import { ${sdkImports.join(', ')} } from '@interactkit/sdk';`,
          "import { Registry } from './type-registry.js';",
          'setRegistry(Registry);',
          ...importLines,
          '',
          flags.dev
            ? `const runtime = new Runtime({ registry: Registry, logger: new DevLogAdapter()${unitPubsub ? `, pubsub: new ${unitPubsub}()` : ''} });`
            : `const runtime = new Runtime({ registry: Registry${unitPubsub ? `, pubsub: new ${unitPubsub}()` : ''} });`,
          ...addLines,
          'await runtime.start();',
          'console.log(`▸ ' + unit.name + ': started ${runtime.size} entities`);',
          '',
          "process.on('SIGINT', async () => {",
          '  await runtime.shutdown();',
          '  process.exit(0);',
          '});',
          '',
        ];
        writeFileSync(resolve(generatedDir, `_${unit.name}.ts`), unitLines.join('\n'), 'utf-8');
      }
      console.log(`  ${plan.units.length} unit entrypoints generated`);

      // Generate _all.ts — single process that runs everything
      const allLines = [
        '// AUTO-GENERATED by interactkit build — do not edit',
        '// Runs all deployment units + hook server in a single process.',
        ...plan.units.map(u => `import './_${u.name}.js';`),
        "import './_hooks.js';",
        '',
      ];
      writeFileSync(resolve(generatedDir, '_all.ts'), allLines.join('\n'), 'utf-8');
    }
  }

  // Step 3: TypeScript compilation → .interactkit/build/
  console.log('▸ tsc');
  mkdirSync(buildDir, { recursive: true });
  try {
    execSync(`npx tsc --outDir "${buildDir}"`, { stdio: 'inherit', cwd });
  } catch {
    process.exit(1);
  }

  // Step 4: Merge generated output into src output so rootDirs imports resolve at runtime
  const generatedBuildDir = resolve(buildDir, '.interactkit/generated');
  const srcBuildDir = resolve(buildDir, 'src');
  if (existsSync(generatedBuildDir) && existsSync(srcBuildDir)) {
    cpSync(generatedBuildDir, srcBuildDir, { recursive: true, force: true });
  }

  // Step 5: Generate Docker deployment files
  if (entities.length > 0 && flags.root) {
    const plan = generateDeploymentPlan(entities);
    const hasMultipleUnits = plan.units.length > 1;
    const hasRemoteHooks = entities.some(e => e.hooks.some(h => !h.inProcess));

    // Dockerfile
    const dockerfile = [
      'FROM node:20-slim AS build',
      'WORKDIR /app',
      'COPY package.json pnpm-lock.yaml* ./',
      'RUN corepack enable && pnpm install --frozen-lockfile',
      'COPY . .',
      'RUN pnpm run build',
      '',
      'FROM node:20-slim',
      'WORKDIR /app',
      'COPY --from=build /app/node_modules ./node_modules',
      'COPY --from=build /app/.interactkit/build ./dist',
      'COPY --from=build /app/config ./config',
      'ENV NODE_ENV=production',
      'CMD ["node", "dist/src/_entry.js"]',
      '',
    ].join('\n');
    writeFileSync(resolve(generatedDir, 'Dockerfile'), dockerfile);

    // docker-compose.single.yml — everything in one container
    const singleCompose: any = {
      services: {
        app: {
          build: { context: '../..', dockerfile: '.interactkit/generated/Dockerfile' },
          env_file: '.env',
          restart: 'unless-stopped',
        },
      },
    };
    if (hasMultipleUnits) {
      singleCompose.services.redis = {
        image: 'redis:7-alpine',
        ports: ['6379:6379'],
      };
      singleCompose.services.app.depends_on = ['redis'];
      singleCompose.services.app.environment = { REDIS_HOST: 'redis', REDIS_PORT: '6379' };
    }
    writeFileSync(resolve(generatedDir, 'docker-compose.single.yml'),
      yamlStringify(singleCompose));

    // docker-compose.yml — distributed: one service per unit + hooks
    if (hasMultipleUnits) {
      const distCompose: any = { services: {} };

      distCompose.services.redis = {
        image: 'redis:7-alpine',
        ports: ['6379:6379'],
        restart: 'unless-stopped',
      };

      for (const unit of plan.units) {
        const svcName = unit.name.replace(/^unit-/, '');
        distCompose.services[svcName] = {
          build: { context: '../..', dockerfile: '.interactkit/generated/Dockerfile' },
          command: `node dist/src/_${unit.name}.js`,
          env_file: '.env',
          environment: { REDIS_HOST: 'redis', REDIS_PORT: '6379' },
          depends_on: ['redis'],
          restart: 'unless-stopped',
          ...(unit.scalable ? { deploy: { replicas: 2 } } : {}),
        };
      }

      if (hasRemoteHooks) {
        distCompose.services.hooks = {
          build: { context: '../..', dockerfile: '.interactkit/generated/Dockerfile' },
          command: 'node dist/src/_hooks.js',
          env_file: '.env',
          environment: { REDIS_HOST: 'redis', REDIS_PORT: '6379' },
          depends_on: ['redis'],
          restart: 'unless-stopped',
        };
      }

      writeFileSync(resolve(generatedDir, 'docker-compose.yml'),
        yamlStringify(distCompose));

      console.log(`  docker: Dockerfile + compose (single + distributed)`);
    } else {
      console.log(`  docker: Dockerfile + compose (single)`);
    }
  }

  console.log('▸ done');
}

/** Minimal YAML serializer for docker-compose (no dependency needed) */
function yamlStringify(obj: any, indent = 0): string {
  const pad = '  '.repeat(indent);
  let out = '';
  for (const [key, val] of Object.entries(obj)) {
    if (val === null || val === undefined) continue;
    if (typeof val === 'string' || typeof val === 'number' || typeof val === 'boolean') {
      out += `${pad}${key}: ${typeof val === 'string' && val.includes(':') ? `"${val}"` : val}\n`;
    } else if (Array.isArray(val)) {
      out += `${pad}${key}:\n`;
      for (const item of val) {
        if (typeof item === 'string') {
          out += `${pad}  - ${item.includes(':') ? `"${item}"` : item}\n`;
        } else {
          out += `${pad}  -\n${yamlStringify(item, indent + 2)}`;
        }
      }
    } else {
      out += `${pad}${key}:\n${yamlStringify(val, indent + 1)}`;
    }
  }
  return out;
}
