import type { EntityInfo } from '@/codegen/types.js';

/**
 * Generate the type-registry.ts source code from extracted entities.
 */
export function emit(entities: EntityInfo[]): string {
  const lines: string[] = [];

  lines.push('// AUTO-GENERATED by @interactkit/sdk codegen — do not edit');
  lines.push("import { z } from '@interactkit/sdk';");
  lines.push('');

  // ─── Registry ─────────────────────────────────────────────
  lines.push('export const Registry = {');
  lines.push('  entities: {');

  for (const entity of entities) {
    lines.push(`    '${entity.type}': {`);

    // State
    if (entity.state.length > 0) {
      const fields = entity.state.map(p => `        ${p.name}: ${p.zodCode}`).join(',\n');
      lines.push(`      state: z.object({\n${fields},\n      }),`);
    } else {
      lines.push('      state: z.object({}),');
    }

    lines.push(`      persona: ${entity.persona},`);

    // Methods
    lines.push('      methods: {');
    for (const method of entity.methods) {
      lines.push(`        '${method.eventName}': {`);
      lines.push(`          input: ${method.inputZod},`);
      lines.push(`          result: ${method.resultZod},`);
      lines.push(`          fieldMeta: ${JSON.stringify(method.fieldMeta)},`);
      lines.push('        },');
    }
    lines.push('      },');

    // Components, streams, refs
    lines.push(`      components: [${entity.components.map(c => `{ property: '${c.propertyName}', type: '${c.entityType}' }`).join(', ')}],`);
    lines.push(`      streams: [${entity.streams.map(s => `'${s.propertyName}'`).join(', ')}],`);
    lines.push(`      refs: [${entity.refs.map(r => `'${r.propertyName}'`).join(', ')}],`);

    // Hooks
    lines.push('      hooks: [');
    for (const hook of entity.hooks) {
      const parts: string[] = [
        `method: '${hook.methodName}'`,
        `type: '${hook.hookTypeName}'`,
      ];
      if (hook.sourcePackage) parts.push(`sourcePackage: '${hook.sourcePackage}'`);
      if (hook.runnerExport) parts.push(`runnerExport: '${hook.runnerExport.replace(/'/g, "\\'")}'`);
      lines.push(`        { ${parts.join(', ')} },`);
    }
    lines.push('      ],');

    // MCP
    if (entity.mcp.isMCPEntity) {
      lines.push('      mcp: {');
      lines.push(`        isMCPEntity: true,`);
      if (entity.mcp.transport) {
        lines.push(`        transport: ${entity.mcp.transport},`);
      }
      lines.push('      },');
    }

    // LLM
    if (entity.llm.isLLMEntity) {
      lines.push('      llm: {');
      lines.push(`        contextProp: ${entity.llm.contextProp ? `'${entity.llm.contextProp}'` : 'undefined'},`);
      lines.push(`        executorProp: ${entity.llm.executorProp ? `'${entity.llm.executorProp}'` : 'undefined'},`);
      lines.push('        tools: [');
      for (const tool of entity.llm.tools) {
        lines.push(`          { method: '${tool.method}', description: '${tool.description.replace(/'/g, "\\'")}', name: ${tool.name ? `'${tool.name}'` : 'undefined'}, input: ${tool.inputZod} },`);
      }
      lines.push('        ],');
      lines.push('      },');
    }

    lines.push('    },');
  }

  lines.push('  },');
  lines.push('} as const;');
  lines.push('');

  // ─── ConfigurableFields ───────────────────────────────────
  lines.push('export const ConfigurableFields = {');
  for (const entity of entities) {
    if (entity.configurables.length === 0) continue;
    lines.push(`  '${entity.type}': [`);
    for (const c of entity.configurables) {
      const parts = [
        `key: '${c.key}'`,
        `label: '${c.label.replace(/'/g, "\\'")}'`,
        c.group ? `group: '${c.group.replace(/'/g, "\\'")}'` : null,
        `type: '${c.tsType}'`,
        `validation: ${c.zodCode}`,
      ].filter(Boolean);
      lines.push(`    { ${parts.join(', ')} },`);
    }
    lines.push('  ],');
  }
  lines.push('} as const;');
  lines.push('');

  // ─── Utility types ────────────────────────────────────────
  lines.push("export type EntityType = keyof typeof Registry['entities'];");

  const allMethods = entities.flatMap(e => e.methods.map(m => m.eventName));
  if (allMethods.length > 0) {
    lines.push(`export type MethodName = ${allMethods.map(m => `'${m}'`).join(' | ')};`);
  } else {
    lines.push('export type MethodName = never;');
  }

  lines.push('');
  return lines.join('\n');
}
